# NumPy Notes and Practicles

#### • It is a linear algebra library for python.
#### • ALMOST all of the other libraries in the PyData EcoSystem rely on NumPy as one of their building blocks.
#### • NumPy is incredibly fast and has bindings with C libraries

In [1]:
import numpy

In [31]:
a = numpy.arange(0,10)

In [38]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
numpy.random.randint(0,20,100)

array([17, 13, 16, 10, 16,  5,  7,  7, 10,  1, 19, 10, 13,  8,  7,  0,  5,
       15, 16,  9, 18,  1,  4,  0, 11,  7,  1, 15,  1,  6,  9,  1,  5, 19,
       18, 18,  2, 14,  8,  3,  7, 10,  2,  5, 12, 19, 16,  6,  5, 18,  3,
       13, 15,  3, 13,  8,  9,  3,  6,  7, 17,  6,  7,  8, 12, 19, 18,  1,
       17,  8,  0, 19,  3, 14,  1, 15,  2, 17, 14,  8, 11, 17, 13, 13, 10,
        6,  1, 19,  6, 10, 17, 14, 14, 18,  4,  1, 13, 17, 11, 14])

In [63]:
numpy.array({1,2})

array({1, 2}, dtype=object)

In [65]:
numpy.random.rand(5,4)


array([[0.69459435, 0.22830263, 0.76402621, 0.15573159],
       [0.46308491, 0.20224539, 0.1675104 , 0.80241098],
       [0.37975484, 0.5130882 , 0.38930733, 0.34257017],
       [0.92583192, 0.78677259, 0.44040465, 0.73131544],
       [0.97470001, 0.56990428, 0.77460072, 0.43600043]])

In [67]:
numpy.random.randn(3,2)

array([[-1.37790338,  0.22292737],
       [-0.82719069,  0.52917481],
       [ 0.28493612, -0.97160726]])

In [4]:
numpy.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

##  Some functions of NumPy discussed but not practiced here are ...

##### np.arange( Start, Stop, Step ) -- Can't give the shape directly, by default, it produces 1-D array of evenly spaced numbers
##### np.ones( Shape )              
##### np.zeros( Shape )
##### np.array( Iterable of Number )          -- To convert other objects into NumPy
##### np.linspace( Start, Stop, Number )  -- Returns the numbers evenly spaced for N times
##### np.eye( Number )                               -- Returns a Square Matrix of 1 in diagonal
##### np.random.rand( Size )               -- Random between 0 to 1 [ Gaussian Distribution ] for N times
##### np.random.randn( Size )             -- Returns random between -1 to 1 both exclusive ( n = "Standard Normal Distrobution )
##### np.random.randint( Start, Stop, Step )
##### arr.reshape(row,col)                          -- Returns but not change inplace
##### arr.resize(row,col)                             -- Inplace change
##### arr.min() / max()                                
##### arr.argmin() / argmax()                     -- Location of that min/max value

# 