# Here we will discuss the Indexing called Position in NumPy!

In [1]:
import numpy as np

### The np's ability to broadcast!

In [2]:
# In normal list...
l = [0]*5
print(l)

[0, 0, 0, 0, 0]


In [5]:
# If I want to update the list with number '3' from 0th index to 3rd
#                                   I would have to run a for loop

l[:3] = 3

TypeError: can only assign an iterable

#### SEE THE BROADCAST!

In [9]:
nArr = np.array(l)

In [10]:
nArr

array([0, 0, 0, 0, 0])

In [25]:
# Now just change!

nArr[:3] = 3

In [26]:
nArr

array([3, 3, 3, 0, 0])

###  

# HERE!

# HERE!

# NumPy applies the same logic of List to assign another - for different you have to use .copy()

###  

In [31]:
np1 = np.arange(1,11)

In [32]:
np2 = np1[2:6].copy()

In [34]:
id(np2)

138515073824

In [35]:
id(np1)

138511878224

###  

###  

# Now the Beast of Indexing. Just. A. BEAST.

#### Two Ways to Index multi dimensioned arrays.

## 1st - Using Two brackets

In [36]:
nArray = np.random.randint(1,100,20).reshape((5,4))

In [37]:
nArray

array([[50, 99, 42, 79],
       [73, 38, 35, 63],
       [84,  4, 90, 55],
       [55, 25, 87, 29],
       [29,  3, 91, 40]])

In [45]:
# Now to Access '63'

nArray[1][3]

63

## 2nd - Using One bracket ( Called a Beast )

In [43]:
nArray[1:3]    # Uupsss... That didn't work!

array([[73, 38, 35, 63],
       [84,  4, 90, 55]])

### Here it is.

In [46]:
nArray[1,3]

63

### NEW ONE RIGHT! AND AMAZING TOO!

###  Works in any number of D, I mean [1,3,1,4] = [1][3][1][4]

###  

###  

# Now, let's grab the Row and Column - Not an element inside as we did there! In the BEAST part

#### Grabbing Row and Column

In [64]:
nArray = np.random.randint(0,50,20).reshape(5,4)

In [65]:
nArray

array([[23,  9, 48, 17],
       [42,  7, 32,  9],
       [20, 39, 30, 11],
       [ 6, 47,  2, 29],
       [49, 41, 10, 44]])

#### Has to be written in ary[Row,Col]

In [66]:
nArray[:3,:2]

array([[23,  9],
       [42,  7],
       [20, 39]])

### Notice? It is the BEAST itself! Just with a use of ':' there. Notice the ',' there!
The BEAST in their language is called 'Fancy Indexing'

In [92]:
nArray[[2,3,1],[1,3,2]]

array([20, 20, 18])

###  Could've also done this ! Pass a list of Rows and Columns to slice selected ones!

###  

###  

###  

# Boolean Indexing

In [76]:
nArray = np.random.randint(0,50,20).reshape(5,4)

In [79]:
nArray

array([[37, 14, 16, 38],
       [19, 45, 18, 17],
       [ 5, 20,  8, 29],
       [31, 45, 30, 20],
       [16, 21, 42, 36]])

In [78]:
nArray <= 30

array([[False,  True,  True, False],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [81]:
nArray[nArray <= 30]

array([14, 16, 19, 18, 17,  5, 20,  8, 29, 30, 20, 16, 21])