# Do not worry, there are no errors in this page.

In [1]:
import numpy as np

In [2]:
nArr = np.arange(10)

In [3]:
nArr + nArr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

And will work for others too... 

In [6]:
(nArr / 3).dtype

dtype('float64')

In [5]:
nArr.dtype

dtype('int32')

### Dividing by Zero in np

In [2]:
np.array([0,1,2]) / 0

<ipython-input-2-b835cfe8a4ff>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,2]) / 0
<ipython-input-2-b835cfe8a4ff>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,2]) / 0


array([nan, inf, inf])

#### 0/0 = nan
#### n/0 = inf

In [3]:
results = np.array([0,1,2]) / 0

<ipython-input-3-5443c6fa6cd7>:1: RuntimeWarning: divide by zero encountered in true_divide
  results = np.array([0,1,2]) / 0
<ipython-input-3-5443c6fa6cd7>:1: RuntimeWarning: invalid value encountered in true_divide
  results = np.array([0,1,2]) / 0


In [5]:
results

array([nan, inf, inf])

In [16]:
type(results[0]) # Type of nan

numpy.float64

In [21]:
type(results[1]) # Type of inf

numpy.float64

In [24]:
results[1]+111

inf

In [27]:
results[0]+10

nan

#### Hmmm... 

###   

###   

# Universal Mathematical functions for NumPy

#### like .sqrt(), .min(), .max(), .exp(), .log(), .sin() etc...
See more at:
https://numpy.org/doc/stable/reference/ufuncs.html